[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@forge-std/=lib/forge-std/src/",
]
etherscan_api_key = "2QECTM4NAYWIRZ8PGIJJNYY3TTXKY9UVUC"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
